# Site settings
title: 魔法小屋
description: "非宁静无以致远"
username: wizjin
timezone: Asia/Shanghai
default_locale: zh-cn
baseurl: ""
url: "http://blog.wizjin.com"

# Build settings
permalink: /:year/:month/:day/:title
highlighter: true
paginate: 5
paginate_path: "/pages/:num"
markdown: kramdown
kramdown:
    input: GFM
exclude: [CNAME, README.md]
