# Site settings
title: 魔法小屋
tagline: "非宁静无以致远"
username: wizjin
timezone: Asia/Shanghai
default_locale: zh-cn
baseurl: ""
url: "http://blog.wizjin.com"

# Build settings
permalink: /:year/:month/:day/:title
pygments: true
paginate: 5
paginate_path: "/pages/:num"
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
exclude: [CNAME, README.md]
